// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AM4.DATA
{
    [Table("Fale_Conosco")]
    public partial class FaleConosco
    {
        [Key]
        [Column("FaleC_ID")]
        public int FaleCId { get; set; }
        [Column("Data_Envio", TypeName = "date")]
        public DateTime DataEnvio { get; set; }
        [Column("IDMensagem")]
        public int Idmensagem { get; set; }
        [Column("IDPessoa")]
        public int Idpessoa { get; set; }

        [ForeignKey(nameof(Idmensagem))]
        [InverseProperty(nameof(Mensagem.FaleConosco))]
        public virtual Mensagem IdmensagemNavigation { get; set; }
        [ForeignKey(nameof(Idpessoa))]
        [InverseProperty(nameof(Pessoa.FaleConosco))]
        public virtual Pessoa IdpessoaNavigation { get; set; }
    }
}